import 'package:university_magazine_project/app/model/user_vo.dart';

final List<UserVO> populatedUsers = [
  // UserVO(
  //   name: "Htet Wai Lwin",
  //   email: "htetwai.18.lwin@gmail.com",
  //   password: "12345678",
  //   role: "s",
  //   status: "a",
  //   facultyId: "F001",
  //   id: "U001",
  //   isLoggedIn: false,
  // ),
  // UserVO(
  //   name: "tin",
  //   email: "tin@gmail.com",
  //   password: "12345678",
  //   role: "Student",
  //   status: "a",
  //   facultyId: "F001",
  //   id: "U002",
  //   isLoggedIn: false,
  // ),
  // UserVO(
  //   name: "Carol Lee",
  //   email: "carol.lee@gmail.com",
  //   password: "12345678",
  //   role: "Coordinator",
  //   status: "a",
  //   facultyId: "F001",
  //   id: "U003",
  //   isLoggedIn: false,
  // ),
  // UserVO(
  //   name: "David Kim",
  //   email: "david.kim@gmail.com",
  //   password: "12345678",
  //   role: "c",
  //   status: "a",
  //   facultyId: "F002",
  //   id: "U004",
  //   isLoggedIn: false,
  // ),
  // UserVO(
  //   name: "Eva Wang",
  //   email: "eva.wang@gmail.com",
  //   password: "12345678",
  //   role: "m",
  //   status: "a",
  //   facultyId: "F000",
  //   id: "U005",
  //   isLoggedIn: false,
  // ),
  UserVO(
    name: "Moe Htet",
    email: "moehtet@gmail.com",
    password: "12345678",
    role: "Admin",
    id: "U001",
    facultyId: "NO Faculty",
    isLoggedIn: false,
  ),
];
